language: node_js
node_js:
  - "7.0"
script:
  - echo "Deploying"
  - npm install
  - npm run build
install:
after_success:
  - npm run firebase -- --token=$FIREBASE_TOKEN
branches:
  only:
    - master
